# Netlify 배포 설정

[build]
# 빌드 명령: pnpm을 사용하여 프로젝트를 빌드합니다.
command = "pnpm build"

# 배포할 디렉토리: Next.js의 빌드 결과물은 .next 폴더에 생성됩니다.
publish = ".next"

[build.environment]
# 사용할 Node.js 버전을 지정합니다. README에서 권장하는 18 버전을 명시합니다.
NODE_VERSION = "18"

# pnpm 버전을 지정하여 Netlify가 pnpm을 사용하도록 합니다.
# 특정 버전 대신 최신 8.x 버전을 사용하도록 설정할 수 있습니다.
PNPM_VERSION = "8"
