export const personalColorTypes = [
  {
    id: "spring-light",
    name: "봄 라이트",
    season: "봄",
    description: "밝고 화사한 톤",
    colors: ["#FFB6C1", "#FFE4B5", "#98FB98", "#87CEEB"],
    colorsName: ["라이트 핑크", "라이트 옐로우", "라이트 그린", "스카이 블루"],
    characteristics: ["밝은 피부톤", "따뜻한 언더톤", "화사한 컬러가 잘 어울림"],
  },
  {
    id: "spring-bright",
    name: "봄 브라이트",
    season: "봄",
    description: "선명하고 생동감 있는 톤",
    colors: ["#FF6347", "#FFD700", "#32CD32", "#1E90FF"],
    colorsName: ["토마토", "골드", "라임 그린", "블루"],
    characteristics: ["생기 있는 피부톤", "따뜻한 언더톤", "선명한 컬러가 잘 어울림"],
  },
  {
    id: "summer-light",
    name: "여름 라이트",
    season: "여름",
    description: "부드럽고 시원한 톤",
    colors: ["#E6E6FA", "#F0F8FF", "#F5F5DC", "#FFE4E1"],
    colorsName: ["라벤더", "앨리스 블루", "베이지", "미스티 로즈"],
    characteristics: ["밝은 피부톤", "차가운 언더톤", "파스텔 컬러가 잘 어울림"],
  },
  {
    id: "summer-mute",
    name: "여름 뮤트",
    season: "여름",
    description: "차분하고 우아한 톤",
    colors: ["#D8BFD8", "#B0C4DE", "#DDA0DD", "#F0E68C"],
    colorsName: ["플럼", "라이트 스틸 블루", "바이올렛", "카키"],
    characteristics: ["중간 톤 피부", "차가운 언더톤", "뮤트한 컬러가 잘 어울림"],
  },
  {
    id: "autumn-mute",
    name: "가을 뮤트",
    season: "가을",
    description: "따뜻하고 차분한 톤",
    colors: ["#CD853F", "#D2691E", "#BC8F8F", "#F4A460"],
    colorsName: ["페루", "초콜릿", "로지 브라운", "샌디 브라운"],
    characteristics: ["따뜻한 피부톤", "따뜻한 언더톤", "어스톤이 잘 어울림"],
  },
  {
    id: "autumn-deep",
    name: "가을 딥",
    season: "가을",
    description: "깊고 진한 톤",
    colors: ["#8B4513", "#A0522D", "#800000", "#556B2F"],
    colorsName: ["새들 브라운", "시에나", "마룬", "다크 올리브 그린"],
    characteristics: ["진한 피부톤", "따뜻한 언더톤", "깊은 컬러가 잘 어울림"],
  },
  {
    id: "winter-bright",
    name: "겨울 브라이트",
    season: "겨울",
    description: "선명하고 강렬한 톤",
    colors: ["#FF1493", "#0000FF", "#FF0000", "#8A2BE2"],
    colorsName: ["딥 핑크", "블루", "레드", "블루 바이올렛"],
    characteristics: ["대비가 강한 피부", "차가운 언더톤", "선명한 컬러가 잘 어울림"],
  },
  {
    id: "winter-deep",
    name: "겨울 딥",
    season: "겨울",
    description: "깊고 세련된 톤",
    colors: ["#000080", "#800080", "#008B8B", "#2F4F4F"],
    colorsName: ["네이비", "퍼플", "다크 시안", "다크 슬레이트 그레이"],
    characteristics: ["진한 피부톤", "차가운 언더톤", "깊은 컬러가 잘 어울림"],
  },
];
